### ISSUE TITLE
[NIA] 클루 유사질문 진행 상황

### ISSUE THREAD

**Issue by yeongsunpark** [yeongsunpark/good#22]
- [x] 유사질문 잘못 들어간 거 수정 하기.
(q_id like "%-2" 인 것 중에 q_id not like "m4_%" 인 것 파악하고 삭제하거나 수정할 수 있는 것 수정하기.)

- [x] 현재 DB에 들어 있는 클루 QA 쌍 중 유사질문이 없는 것만 뽑아 내서 알바에게 전달 요청

- [x] 제작된 유사 질문 DB 적재 (4월 말까지 반드시)

**Comment by yeongsun** [comment]
완료. 최종 검수만 남음.
